In [1]:
import pandas as pd
import numpy as np

In [3]:
import glob

path = r'D:\icfoss\Project' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=None, names = ['Quotes', 'Tags'])
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=True)

In [4]:
df.to_csv('quotes.csv')

In [5]:
df.head()

Quotes    Tags
0  Take chances, make mistakes. That's how you gr...  Chance
1  The biggest risk is not taking any risk... In ...  Chance
2  Take risks. Ask big questions. Don't be afraid...  Chance
3  Luck always favours the brave. And you must re...  Chance
4  You have to take risks. We will only understan...  Chance

In [6]:
df = df.dropna()

In [35]:
mapp

{'Motivational': 0,
 'Inspirational': 1,
 'Freedom': 2,
 'Work': 3,
 'Chance': 4,
 'Failure': 5,
 'Life': 6,
 'Knowledge': 7,
 'Sympathy': 8,
 'Strength': 9}

In [10]:
mapp = {}
for i in range(0,11):
    s = input("Key")
    n = int(input("Value"))
    mapp[s] = n
    
    

KeyMotivational
Value0
KeyInspirational
Value1
KeyFreedom
Value2
KeyWork
Value3
KeyChance
Value4
KeyFailure
Value5
KeyLife
Value6
KeyKnowledge
Value7
KeySympathy
Value8
KeyStrength
Value9
Key
Value


ValueError: invalid literal for int() with base 10: ''

In [12]:
df.Quotes

0       Take chances, make mistakes. That's how you gr...
1       The biggest risk is not taking any risk... In ...
2       Take risks. Ask big questions. Don't be afraid...
3       Luck always favours the brave. And you must re...
4       You have to take risks. We will only understan...
                              ...                        
2763    I work out not to lose weight but to maintain ...
2764    How do you deal with a criminal that will not ...
2765    Nobody in Europe will be abandoned. Nobody in ...
2766    You don't work on something for six years and ...
2767    Conservatism is the perfect antidote to underd...
Name: Quotes, Length: 2767, dtype: object

In [13]:
quote = df.Quotes
tags = df.Tags

In [14]:
df['label'] = df.Tags.map(mapp)

In [15]:
x = df.Quotes
y = df.label

In [16]:
print(x.shape)
print(y.shape)

(2767,)
(2767,)


In [17]:
df

Quotes    Tags  label
0     Take chances, make mistakes. That's how you gr...  Chance      4
1     The biggest risk is not taking any risk... In ...  Chance      4
2     Take risks. Ask big questions. Don't be afraid...  Chance      4
3     Luck always favours the brave. And you must re...  Chance      4
4     You have to take risks. We will only understan...  Chance      4
...                                                 ...     ...    ...
2763  I work out not to lose weight but to maintain ...    Work      3
2764  How do you deal with a criminal that will not ...    Work      3
2765  Nobody in Europe will be abandoned. Nobody in ...    Work      3
2766  You don't work on something for six years and ...    Work      3
2767  Conservatism is the perfect antidote to underd...    Work      3

[2767 rows x 3 columns]

In [18]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.20, random_state =26)

In [19]:
y_train

673     2
469     5
2728    3
1977    9
2262    8
       ..
1986    9
1457    6
1799    0
1342    7
821     2
Name: label, Length: 2213, dtype: int64

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')

In [21]:
vect.fit(X_train)
vect.vocabulary_

{'freedom': 1944,
 'thank': 4777,
 'god': 2057,
 'failures': 1728,
 'maybe': 2980,
 'time': 4825,
 'reflection': 3883,
 'feel': 1797,
 'like': 2805,
 'failure': 1727,
 'just': 2635,
 'tried': 4915,
 'failed': 1723,
 'run': 4090,
 'away': 353,
 'laziness': 2728,
 'work': 5255,
 'hard': 2191,
 'touch': 4865,
 'intuition': 2558,
 'listen': 2828,
 'heart': 2226,
 'marketing': 2948,
 'directors': 1310,
 'dream': 1400,
 'strength': 4554,
 'growth': 2132,
 'come': 843,
 'continuous': 976,
 'effort': 1483,
 'struggle': 4578,
 'interested': 2546,
 'picking': 3486,
 'crumbs': 1075,
 'compassion': 879,
 'thrown': 4814,
 'table': 4695,
 'considers': 946,
 'master': 2964,
 'want': 5146,
 'menu': 3012,
 'rights': 4028,
 'today': 4840,
 'choose': 755,
 'life': 2791,
 'morning': 3097,
 'wake': 5139,
 'joy': 2621,
 'happiness': 2189,
 'negativity': 3183,
 'pain': 3359,
 'comes': 846,
 'able': 42,
 'continue': 972,
 'make': 2920,
 'mistakes': 3067,
 'choices': 753,
 'deny': 1198,
 'humanity': 2328,
 'em

In [22]:
vectorizer = vect.fit(x)

In [23]:
vectorizer

CountVectorizer(stop_words='english')

In [24]:
vect.vocabulary_

{'chances': 803,
 'make': 3270,
 'mistakes': 3432,
 'grow': 2387,
 'pain': 3758,
 'nourishes': 3597,
 'courage': 1153,
 'fail': 1945,
 'order': 3692,
 'practice': 4024,
 'brave': 607,
 'biggest': 516,
 'risk': 4516,
 'taking': 5255,
 'world': 5909,
 'changing': 807,
 'really': 4296,
 'quickly': 4223,
 'strategy': 5090,
 'guaranteed': 2394,
 'risks': 4518,
 'ask': 322,
 'big': 514,
 'questions': 4220,
 'don': 1556,
 'afraid': 165,
 'reaching': 4275,
 'far': 1983,
 'luck': 3237,
 'favours': 2007,
 'remember': 4390,
 'people': 3835,
 'follow': 2118,
 'heart': 2496,
 'life': 3132,
 'means': 3343,
 'say': 4625,
 'believe': 479,
 'power': 4019,
 'greater': 2361,
 'yes': 5951,
 'understand': 5573,
 'miracle': 3419,
 'fully': 2215,
 'allow': 200,
 'unexpected': 5586,
 'happen': 2447,
 'beware': 506,
 'missing': 3428,
 'altogether': 210,
 'late': 3045,
 'day': 1265,
 'wrong': 5936,
 'decision': 1290,
 'preferable': 4045,
 'terror': 5332,
 'indecision': 2747,
 'comes': 956,
 'willing': 5854,
 'u

In [25]:
print(vect.get_feature_names())


['000', '10', '100', '11', '111', '11th', '12', '13', '130', '137', '14', '140', '15', '150', '16', '17', '18', '19', '1917', '1923', '1958', '1990s', '20', '200', '2014', '20s', '20th', '22', '24', '27', '28', '30', '30th', '338', '40', '50', '50s', '80', '82', '83', '90', '92', '99', 'aagadu', 'abandon', 'abandoned', 'abdominal', 'abe', 'abilities', 'ability', 'ablaze', 'able', 'abolish', 'abortion', 'abridging', 'abroad', 'absence', 'absolutely', 'absorbed', 'absorbing', 'abundance', 'abuse', 'abuses', 'abusive', 'academia', 'academy', 'accept', 'acceptance', 'accepted', 'accepting', 'access', 'accessible', 'accident', 'acclaim', 'accompanied', 'accomplish', 'accomplished', 'accomplishment', 'accomplishments', 'accordance', 'according', 'accordingly', 'accords', 'account', 'accumulate', 'accuracy', 'accurate', 'accurately', 'accuse', 'accused', 'ache', 'achieve', 'achieved', 'achievement', 'achievements', 'achieves', 'achieving', 'acknowledge', 'acknowledged', 'acquire', 'acquired',

In [26]:
print(len(vect.get_feature_names()))

5967


In [27]:
X_train_transformed = vect.transform(X_train)
X_test_transformed =vect.transform(X_test)

In [28]:
print(X_train_transformed)

  (0, 2184)	1
  (1, 1946)	1
  (1, 1950)	1
  (1, 1951)	1
  (1, 2024)	1
  (1, 2306)	1
  (1, 2959)	1
  (1, 3147)	1
  (1, 3337)	1
  (1, 4336)	1
  (1, 5342)	1
  (1, 5394)	1
  (1, 5499)	1
  (2, 404)	1
  (2, 1477)	1
  (2, 1581)	1
  (2, 2456)	1
  (2, 2496)	1
  (2, 2875)	1
  (2, 3064)	1
  (2, 3172)	1
  (2, 3301)	1
  (2, 4572)	1
  (2, 5439)	1
  (2, 5900)	1
  :	:
  (2209, 3447)	1
  (2210, 412)	1
  (2210, 2166)	1
  (2210, 2309)	1
  (2210, 4127)	1
  (2210, 5354)	1
  (2210, 5946)	1
  (2211, 51)	1
  (2211, 503)	1
  (2211, 2323)	1
  (2211, 2695)	1
  (2211, 3015)	1
  (2211, 3796)	1
  (2211, 5574)	1
  (2211, 5691)	1
  (2212, 223)	1
  (2212, 1177)	1
  (2212, 1927)	1
  (2212, 2184)	1
  (2212, 2263)	1
  (2212, 3651)	1
  (2212, 3694)	1
  (2212, 3835)	1
  (2212, 3923)	1
  (2212, 4461)	1


In [29]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

# fit
naive_model = mnb.fit(X_train_transformed,y_train)

# predict class
y_pred_class = mnb.predict(X_test_transformed)

In [30]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

y_pred_class

# confusion matrix
x = metrics.confusion_matrix(y_test, y_pred_class)
x

array([[18,  8,  0,  7,  2,  7,  2,  2,  1,  4],
       [ 3, 22,  1,  8,  6,  1,  5,  3,  3,  2],
       [ 0,  6, 49,  0,  0,  0,  2,  1,  1,  2],
       [ 0,  1,  1, 38,  2,  3,  1,  1,  0,  1],
       [ 1,  2,  2,  3, 47,  3,  2,  0,  0,  0],
       [ 0,  0,  2,  0,  3, 48,  2,  0,  0,  1],
       [ 0,  3,  0,  1,  4,  2, 52,  0,  2,  1],
       [ 1,  1,  0,  0,  1,  0,  0, 43,  0,  2],
       [ 2,  0,  0,  0,  1,  0,  2,  2, 39,  2],
       [ 2,  2,  2,  0,  3,  1,  1,  3,  0, 49]], dtype=int64)

In [32]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
#[row, column]
TN = confusion[1, 1]
FP = confusion[1, 0]
FN = confusion[0, 1]
TP = confusion[0, 0]

[[18  8  0  7  2  7  2  2  1  4]
 [ 3 22  1  8  6  1  5  3  3  2]
 [ 0  6 49  0  0  0  2  1  1  2]
 [ 0  1  1 38  2  3  1  1  0  1]
 [ 1  2  2  3 47  3  2  0  0  0]
 [ 0  0  2  0  3 48  2  0  0  1]
 [ 0  3  0  1  4  2 52  0  2  1]
 [ 1  1  0  0  1  0  0 43  0  2]
 [ 2  0  0  0  1  0  2  2 39  2]
 [ 2  2  2  0  3  1  1  3  0 49]]


In [33]:
precision = TP / float(TP + FP)

print("precision",precision)
# print(metrics.precision_score(y_test, y_pred_class))

precision 0.8571428571428571


In [34]:
import joblib
fin_model = naive_model
joblib.dump(fin_model, 'naive_model2.joblib')
joblib.dump(vectorizer, 'CountVectorizer2.joblib')

['CountVectorizer2.joblib']

In [ ]:
pwd